# MPLAB IDE generated this makefile for use with GNU make.
# Project: WFF_GenericHID_Demo_3.mcp
# Date: Thu Jul 12 16:27:24 2012

AS = MPASMWIN.exe
CC = mcc18.exe
LD = mplink.exe
AR = mplib.exe
RM = rm

WFF_GenericHID_Demo_3.cof : main.o debug.o usb_descriptors.o usb_function_hid.o usb_device.o 5110_lcd.o i2c.o ds1621.o ds1307.o cam.o uart.o keyboard.o scancodes.o
	$(LD) /p18F4550 /l"C:\Program Files (x86)\Microchip\mplabc18\v3.37.01\lib" "rm18f4550 - HID Bootload.lkr" "main.o" "debug.o" "usb_descriptors.o" "usb_function_hid.o" "usb_device.o" "5110_lcd.o" "i2c.o" "ds1621.o" "ds1307.o" "cam.o" "uart.o" "keyboard.o" "scancodes.o" /u_CRUNTIME /u_DEBUG /z__MPLAB_BUILD=1 /z__MPLAB_DEBUG=1 /z__MPLAB_DEBUGGER_PICKIT2=1 /z__ICD2RAM=1 /o"WFF_GenericHID_Demo_3.cof" /M"WFF_GenericHID_Demo_3.map" /W

main.o : main.c C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/string.h ds1307.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/stdio.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/stdlib.h USB/usb_common.h USB/usb_device.h USB/usb_hal.h debug.h LCD/5110_lcd.h uart.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/delays.h main.c C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/stddef.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/p18F4550.h PS2/keyboard.h PS2/keycodes.h ds1621.h HardwareProfile.h USB/usb.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/GenericTypeDefs.h Compiler.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/p18cxxx.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/p18f4550.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/stdarg.h usb_config.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/limits.h USB/usb_ch9.h USB/usb_hal_pic18.h USB/usb_function_hid.h cam.h camCom.h
	$(CC) -p=18F4550 "main.c" -fo="main.o" -D__DEBUG -D__MPLAB_DEBUGGER_PICKIT2=1 -mL -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

debug.o : debug.c C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/string.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/stdio.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/stdlib.h USB/usb_common.h USB/usb_device.h USB/usb_hal.h debug.h debug.c C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/stddef.h HardwareProfile.h USB/usb.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/GenericTypeDefs.h Compiler.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/p18cxxx.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/p18f4550.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/stdarg.h usb_config.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/limits.h USB/usb_ch9.h USB/usb_hal_pic18.h USB/usb_function_hid.h
	$(CC) -p=18F4550 "debug.c" -fo="debug.o" -D__DEBUG -D__MPLAB_DEBUGGER_PICKIT2=1 -mL -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

usb_descriptors.o : usb_descriptors.c C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/stdio.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/stdlib.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/string.h USB/usb_common.h USB/usb_device.h USB/usb_hal.h usb_descriptors.c HardwareProfile.h USB/usb.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/GenericTypeDefs.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/stddef.h Compiler.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/p18cxxx.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/p18f4550.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/stdarg.h usb_config.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/limits.h USB/usb_ch9.h USB/usb_hal_pic18.h USB/usb_function_hid.h
	$(CC) -p=18F4550 "usb_descriptors.c" -fo="usb_descriptors.o" -D__DEBUG -D__MPLAB_DEBUGGER_PICKIT2=1 -mL -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

usb_function_hid.o : usb_function_hid.c C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/stdio.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/stdlib.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/string.h USB/usb_common.h USB/usb_device.h USB/usb_hal.h usb_function_hid.c C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/GenericTypeDefs.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/stddef.h Compiler.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/p18cxxx.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/p18f4550.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/stdarg.h USB/usb.h usb_config.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/limits.h USB/usb_ch9.h USB/usb_hal_pic18.h USB/usb_function_hid.h
	$(CC) -p=18F4550 "usb_function_hid.c" -fo="usb_function_hid.o" -D__DEBUG -D__MPLAB_DEBUGGER_PICKIT2=1 -mL -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

usb_device.o : USB/usb_device.c C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/stdio.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/stdlib.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/string.h USB/usb_common.h USB/usb_device.h USB/usb_hal.h USB/usb_device.c USB/usb.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/GenericTypeDefs.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/stddef.h Compiler.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/p18cxxx.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/p18f4550.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/stdarg.h usb_config.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/limits.h USB/usb_ch9.h USB/usb_hal_pic18.h HardwareProfile.h USB/usb_device_local.h
	$(CC) -p=18F4550 "USB\usb_device.c" -fo="usb_device.o" -D__DEBUG -D__MPLAB_DEBUGGER_PICKIT2=1 -mL -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

5110_lcd.o : LCD/5110_lcd.c LCD/5110_lcd.h LCD/font.h LCD/5110_lcd.c C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/p18F4550.h
	$(CC) -p=18F4550 "LCD\5110_lcd.c" -fo="5110_lcd.o" -D__DEBUG -D__MPLAB_DEBUGGER_PICKIT2=1 -mL -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

i2c.o : i2c.c i2c.h i2c.c C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/p18F4550.h
	$(CC) -p=18F4550 "i2c.c" -fo="i2c.o" -D__DEBUG -D__MPLAB_DEBUGGER_PICKIT2=1 -mL -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

ds1621.o : ds1621.c i2c.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/delays.h ds1621.c ds1621.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/p18cxxx.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/p18f4550.h
	$(CC) -p=18F4550 "ds1621.c" -fo="ds1621.o" -D__DEBUG -D__MPLAB_DEBUGGER_PICKIT2=1 -mL -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

ds1307.o : ds1307.c ds1307.h i2c.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/delays.h ds1307.c C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/p18cxxx.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/p18f4550.h
	$(CC) -p=18F4550 "ds1307.c" -fo="ds1307.o" -D__DEBUG -D__MPLAB_DEBUGGER_PICKIT2=1 -mL -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

cam.o : cam.c delay.h cam.h camCom.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/p18F4550.h
	$(CC) -p=18F4550 "cam.c" -fo="cam.o" -D__DEBUG -D__MPLAB_DEBUGGER_PICKIT2=1 -mL -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

uart.o : uart.c C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/string.h uart.h uart.c C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/p18F4550.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/stddef.h
	$(CC) -p=18F4550 "uart.c" -fo="uart.o" -D__DEBUG -D__MPLAB_DEBUGGER_PICKIT2=1 -mL -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

keyboard.o : PS2/keyboard.c C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/stdio.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/stdlib.h PS2/scancodes.h PS2/keyboard.c C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/stdarg.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/stddef.h C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.37.01/h/p18F4550.h PS2/keycodes.h
	$(CC) -p=18F4550 "PS2\keyboard.c" -fo="keyboard.o" -D__DEBUG -D__MPLAB_DEBUGGER_PICKIT2=1 -mL -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

scancodes.o : PS2/scancodes.c PS2/scancodes.h PS2/scancodes.c PS2/keycodes.h
	$(CC) -p=18F4550 "PS2\scancodes.c" -fo="scancodes.o" -D__DEBUG -D__MPLAB_DEBUGGER_PICKIT2=1 -mL -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

clean : 
	$(RM) "main.o" "debug.o" "usb_descriptors.o" "usb_function_hid.o" "usb_device.o" "5110_lcd.o" "i2c.o" "ds1621.o" "ds1307.o" "cam.o" "uart.o" "keyboard.o" "scancodes.o" "WFF_GenericHID_Demo_3.cof" "WFF_GenericHID_Demo_3.hex"

