using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.IO;
using System.Text.RegularExpressions;
using System.Diagnostics;
using System.Globalization;
using System;
 
namespace TextExtractor
{
    // extract meaningful text from text files generated by converting HTML to text
    // Data source if Geocities Data Dump from www.archive.org
    class Program
    {
        enum InputParagraphType
        {
            Complete,
            Fragmented,
            Concatenated,
            ParagraphTooShort,
            SentenceTooShort,
            FewSentences,
            Invalid,
            WithURLs,
            TooManyUpperCases,
            DigitsOrSymbols,
            Undefined
        }

        private const string alphaNumericCharSet = "abcdefghijklmnopqrstuvwxyz0123456789";
        private const string numericCharSet = "0123456789";
        private const string specialSymbol = "~@#$%^&*<>+"; // only special symbols unlikely to be used in normal sentences, excluding - () etc.
        static char[] puncChars = { '.', ',', '?', '!', ':', '|' };
        static char[] spaceChars = new char[] { ' ', (char)160 };

        static string[] ignoredWordList;
        static string[] preferredWordList;
        static string[] avoidedWordList;
        static string[] personalList;

        static string[] moodHappyList;
        static string[] moodSadList;
        static string[] moodIncreaseList;
        static string[] moodDecreaseList;

        static Dictionary<InputParagraphType, List<string>> sortedParagraphs = new Dictionary<InputParagraphType, List<string>>();
        static Dictionary<int, string> sortedParagraphSource = new Dictionary<int, string>(); // key is the index of the sorted paragraph (only for type 'complete'), value is the filename without extension
        static Dictionary<int, string> extractedTextSource = new Dictionary<int, string>(); // key is the index of the line of the extracted text in the extracted text file, value is the filename without extension
        static Dictionary<string, int> paraRelevantHash = new Dictionary<string, int>();
        static Dictionary<string, bool> paraPoemHash = new Dictionary<string, bool>();

        static void Main(string[] args)
        {
            string outputFileSelPara = @"C:\temp\onlyThoughts\extracted_text\selected_para.txt";
            string outputParaFile = @"C:\temp\onlyThoughts\extracted_text\paragraphs.csv";
            string outputTopicFile = @"C:\temp\onlyThoughts\extracted_text\topics.csv";
            string outputParaTopicFile = @"C:\temp\onlyThoughts\extracted_text\para_topics.csv";

            string inputTextDir = @"D:\temp\geocities_large_6mil";

            DateTime startTime = DateTime.Now;
            writeLog("Starting ...");

            /*
            if (!Directory.Exists(Path.GetDirectoryName(outputFileSelPara)))
                Directory.CreateDirectory(Path.GetDirectoryName(outputFileSelPara));
            */ 

            if (!Directory.Exists(Path.GetDirectoryName(outputParaFile)))
                Directory.CreateDirectory(Path.GetDirectoryName(outputParaFile));

            if (!Directory.Exists(Path.GetDirectoryName(outputTopicFile)))
                Directory.CreateDirectory(Path.GetDirectoryName(outputTopicFile));

            if (!Directory.Exists(Path.GetDirectoryName(outputParaTopicFile)))
                Directory.CreateDirectory(Path.GetDirectoryName(outputParaTopicFile));

            Dictionary<string, long> countPerDomain = new Dictionary<string, long>();
            Dictionary<string, string> retValBySource = new Dictionary<string, string>();
            Dictionary<string, List<string>> retValByTopic = new Dictionary<string, List<string>>();

            Console.BufferHeight = 30000;
            Console.WindowHeight = 40;
            Console.WindowWidth = 120;

            if (File.Exists(outputParaFile))
                File.Delete(outputParaFile);

            if (File.Exists(outputTopicFile))
                File.Delete(outputTopicFile);

            if (File.Exists(outputParaTopicFile))
                File.Delete(outputParaTopicFile);

            ignoredWordList = File.ReadAllLines("ignored.txt").Where(x => !string.IsNullOrEmpty(x)).Select(x => x.Trim()).Distinct().ToArray();
            preferredWordList = File.ReadAllLines("preferred.txt").Where(x => !string.IsNullOrEmpty(x)).Select(x => x.Trim()).Distinct().ToArray();
            avoidedWordList = File.ReadAllLines("avoided.txt").Where(x => !string.IsNullOrEmpty(x)).Select(x => x.Trim()).Distinct().ToArray();
            
            moodHappyList = File.ReadAllLines("moodHappy.txt").Where(x => !string.IsNullOrEmpty(x)).Select(x => x.Trim()).Distinct().ToArray();
            moodSadList = File.ReadAllLines("moodSad.txt").Where(x => !string.IsNullOrEmpty(x)).Select(x => x.Trim()).Distinct().ToArray();
            moodIncreaseList = File.ReadAllLines("moodIncrease.txt").Where(x => !string.IsNullOrEmpty(x)).Select(x => x.Trim()).Distinct().ToArray();
            moodDecreaseList = File.ReadAllLines("moodDecrease.txt").Where(x => !string.IsNullOrEmpty(x)).Select(x => x.Trim()).Distinct().ToArray();
            personalList = File.ReadAllLines("personal.txt").Where(x => !string.IsNullOrEmpty(x)).Select(x => x.Trim()).Distinct().ToArray();

            /*
            writeLog(String.Format("Analyzing text files in directory {0}", inputTextDir));
            AnalyzeDirectory(inputTextDir, "*.txt");
            writeLog(String.Format("Done analyzing directory. Added: {0}, Skipped: {1}. Total Files: {2}. Total Dirs: {3}", countAdded, countIgnored, countTotal, countDir));

            ExtractTextToFile(outputFileSelPara);

            if (!File.Exists(outputFileSelPara))
            {
                writeLog("Text extraction fails. Press any key to quit.");
                Console.ReadLine();
                return;
            }
            */

            Dictionary<string, List<string>> retValByContent = CategorizeText(outputFileSelPara, ref retValByTopic, ref retValBySource);

            writeLog("Writing topics and paragraph files ...");

            // output significant topics only
            retValByTopic = retValByTopic.Where(p => retValByTopic[p.Key].Count >= 20).ToDictionary(p => p.Key, p => p.Value);
            var retValTopicArray = retValByTopic.Keys.ToList();
            StringBuilder sbTopicList = new StringBuilder();
            sbTopicList.Append("topic_index,topic_name,mixed_case_count,paragraph_count,word_count" + Environment.NewLine);
            int countTopicWritten = 0;
            for (int k = 0; k < retValTopicArray.Count; k++)
            {
                if (countTopicWritten % 500 == 0)
                    writeLog(String.Format("{0} / {1} topics written ({2:0.00}%)", countTopicWritten, retValTopicArray.Count, countTopicWritten * 100.0 / retValTopicArray.Count));

                var topic = retValTopicArray[k];
                int mixed_case_count = 0;

                var words = topic.Split(spaceChars, StringSplitOptions.RemoveEmptyEntries);
                for (int i = 0; i < words.Length; i++)
                {
                    var word = words[i];

                    // mixed case word are usually special term (e.g. PhD)
                    if (word.Length >= 3)
                    {
                        string temp = Char.ToLower(word[0]) + word.Substring(1);
                        if (temp.ToLower() != temp && temp.ToUpper() != temp)
                        {
                            mixed_case_count++;
                        }
                    }
                }

                sbTopicList.Append(String.Format("{0},{1},{2},{3},{4}{5}", k, StringToCSVCell(topic), mixed_case_count, retValByTopic[topic].Count, words.Length, Environment.NewLine));
                countTopicWritten++;
            }
            File.AppendAllText(outputTopicFile, sbTopicList.ToString());
            writeLog(String.Format("Done. {0} / {1} topics written", countTopicWritten, retValTopicArray.Count));

            // select significant paragraphs only
            var paraWithTags = retValByContent.Where(p => retValByContent[p.Key].Count >= 3).OrderByDescending(p => paraRelevantHash[getMD5Hash(p.Key)]).ThenByDescending(p => retValByContent[p.Key].Count).ToDictionary(p => p.Key, p => p.Value);
            StringBuilder sbParaTopic = new StringBuilder();
            StringBuilder sbParaContent = new StringBuilder();

            // paragraph topic connector
            int rel_count = 0;

            sbParaTopic.Append("rel_index,para_index,topic_index" + Environment.NewLine);
            sbParaContent.Append("para_index,content,number_count,name_count,exclamation_count,colon_count,mixed_case_count,question_count,content_score,word_count,phrase_count,topic_count,personal_count,length,popularity,mood_score,is_poem" + Environment.NewLine);
            int countParaWritten = 0;
            for (int para_index = 0; para_index<paraWithTags.Keys.Count; para_index++)
            {
                if (countParaWritten % 500 == 0)
                    writeLog(String.Format("{0} / {1} paragraph written ({2:0.00}%)", countParaWritten, paraWithTags.Keys.Count, countParaWritten * 100.0 / paraWithTags.Keys.Count));

                var para = paraWithTags.Keys.ToArray()[para_index];

                string paraMD5 = getMD5Hash(para);

                int isPoem = paraPoemHash.ContainsKey(paraMD5) ? 1 : 0;

                int mixed_case_count = 0;
                int number_count = 0;

                int name_count = 0;

                int exclamation_count = 0;
                int colon_count = 0;
                int question_count = 0;

                int paraScore = 0;
                int popularity = 0;
                double paraMood = 0;

                int phraseCount = 0;
                int wordCount = 0;
                int topicCount = 0;

                int personalCount = 0;

                try
                {
                    var paraTags = paraWithTags[para];
                    topicCount = paraTags.Count;
                    foreach (var paraTag in paraTags)
                    {
                        if (retValByTopic.ContainsKey(paraTag))
                            popularity += retValByTopic[paraTag].Count;
                    }
                    
                    exclamation_count = para.Count(c => c == '!');
                    colon_count = para.Count(c => c == ':');
                    question_count = para.Count(c => c == '?');

                    var paraSentences = para.Split(puncChars,  StringSplitOptions.RemoveEmptyEntries);
                    foreach (var sentence in paraSentences)
                    {
                        var words = sentence.Split(spaceChars, StringSplitOptions.RemoveEmptyEntries);

                        for (int i = 0; i < words.Length; i++)
                        {
                            var word = words[i].Trim();
                            if (word.Length == 0)
                                continue;

                            if (i > 0 && word.Length >= 3 && word != word.ToLower())
                            {
                                name_count++;
                            }

                            if (moodHappyList.Where(x => String.Compare(x.ToLower(), word.ToLower()) == 0).ToList().Count() > 0)
                            {
                                paraMood++;
                            }                            
                            else if (moodSadList.Where(x => String.Compare(x.ToLower(), word.ToLower()) == 0).ToList().Count() > 0)
                            {
                                paraMood--;
                            }
                            else if (moodIncreaseList.Where(x => String.Compare(x.ToLower(), word.ToLower()) == 0).ToList().Count() > 0)
                            {
                                paraMood = paraMood * 1.1;
                            }
                            else if (moodDecreaseList.Where(x => String.Compare(x.ToLower(), word.ToLower()) == 0).ToList().Count() > 0)
                            {
                                paraMood = paraMood / 1.1;
                            }

                            if (personalList.Where(x => String.Compare(x.ToLower(), word.ToLower()) == 0).ToList().Count() > 0)
                            {
                                personalCount++;
                            }

                            if (word.Where(x => Char.IsDigit(x)).Any())
                            {
                                number_count++;
                            }

                            // mixed case word are usually some abbrev. or special terms (e.g. iOS, PhD, etc.)
                            if (word.Length >= 3)
                            {
                                string temp = Char.ToLower(word[0]) + word.Substring(1);
                                if (temp.ToLower() != temp && temp.ToUpper() != temp)
                                {
                                    mixed_case_count++;
                                }
                            }
                            
                            wordCount++;
                        }
                        phraseCount++;
                    }

                    // mood increase or decrease depending on the punctuation in the paragraph
                    paraMood = paraMood * (question_count + 1); 
                    paraMood = paraMood * (exclamation_count + 1);
                    paraMood = 100 * paraMood;

                    paraScore = paraRelevantHash[paraMD5];
                }
                catch (Exception ex)
                {
                    writeLog(ex.Message);
                }

                foreach (var topic in paraWithTags[para])
                {
                    int topicInd = retValTopicArray.IndexOf(topic);
                    if (topicInd >= 0)
                    {
                        sbParaTopic.Append(String.Format("{0},{1},{2}{3}", rel_count, para_index, topicInd, Environment.NewLine));
                    }
                    rel_count++;
                }

                sbParaContent.Append(String.Format("{0},{1},{2},{3},{4},{5},{6},{7},{8},{9},{10},{11},{12},{13},{14},{15},{16}{17}",
                                                    para_index, StringToCSVCell(formatPunctuation(para).Trim()), number_count, name_count, exclamation_count,
                                                    colon_count, mixed_case_count, question_count, paraScore,
                                                    wordCount, phraseCount, topicCount, personalCount, para.Length, popularity, (int)paraMood, isPoem,
                                                    Environment.NewLine));

                countParaWritten++;
            }
            File.AppendAllText(outputParaTopicFile, sbParaTopic.ToString());
            File.AppendAllText(outputParaFile, sbParaContent.ToString());

            writeLog(String.Format("Done. {0} / {1} paragraphs written", countParaWritten, paraWithTags.Keys.Count));
            Console.WriteLine();
            writeLog("Top 10 domains with selected paragraphs:");
            Console.WriteLine();

            var selDomain = (from entry in countPerDomain orderby entry.Value descending select entry.Key).Take(10).ToList();
            foreach (var domain in selDomain)
            {
                Console.WriteLine(String.Format("{0,20}: {1}", domain, countPerDomain[domain]));
            }

            Console.WriteLine();
            Console.WriteLine(DateTime.Now + " - Done. Duration: {0} secs ...", (int)(DateTime.Now - startTime).TotalSeconds);
            Console.ReadLine();
        }

        static Dictionary<string, List<string>> CategorizeText(string inputFile, ref Dictionary<string, List<string>> retValByTopic, ref Dictionary<string, string> retValSource)
        {
            // ref Dictionary<int, string> retValSource: key is md5 of paragraph, value is name of file where paragraph comes from
            // Dictionary<string, List<string>> retValByTopic = new Dictionary<string, List<string>>(); // key is topic, value is list of paragraphs in that topic
            Dictionary<string, List<string>> retValByContent = new Dictionary<string, List<string>>(); // key is paragraph, value is topic for that paragraph

            Console.WriteLine(String.Format("{0} - Start categorizing text in {1} ...", DateTime.Now, inputFile));

            StreamReader sr = File.OpenText(inputFile); //.Where(x => !string.IsNullOrEmpty(x)).Select(x => x.Trim()).Distinct().ToArray();
            int paraCount = 0;
            while (!sr.EndOfStream)
            {
                var paragraph = sr.ReadLine();

                // here we assume the line index in the text file corresponds to the line index in the extractedTextSource variable, generated when extracting the text
                // retValSource[getMD5Hash(paragraph)] = extractedTextSource[paraCount];

                if (paraCount % 500 == 0)
                    Console.WriteLine(String.Format("{0} - {1} paragraphs read. {2} topics", DateTime.Now, paraCount, retValByTopic.Keys.Count));

                List<string> topics = findWordCombinations(paragraph, 2, 6);
                foreach (var topic in topics)
                {
                    if (!retValByTopic.ContainsKey(topic))
                    {
                        List<string> paraList = new List<string>();
                        paraList.Add(paragraph);
                        retValByTopic[topic] = paraList;
                    }
                    else
                    {
                        retValByTopic[topic].Add(paragraph);
                    }
                }

                paraCount++;
            }
            sr.Close();

            Console.WriteLine(String.Format("{0} - Done. {1} paragraphs read. {2} topics. Processing results ...", DateTime.Now, paraCount, retValByTopic.Keys.Count));

            int countSelected = 0;
            int countProcessed = 0;
            int countNoURL = 0;
            foreach (var topic in retValByTopic.Keys)
            {
                if (countProcessed % 500 == 0)
                    Console.WriteLine(String.Format("{0} - {1} topics ({2} paragraphs) selected, {3} without URLs, {4} / {5} processed ({6:0.00}%)",
                        DateTime.Now, countSelected, retValByContent.Keys.Count, countNoURL, countProcessed, retValByTopic.Keys.Count, countProcessed * 100.0 / retValByTopic.Keys.Count));

                List<string> paraList = retValByTopic[topic];

                if (paraList.Count() >= 20)
                {
                    Dictionary<int, int> paraRelevant = new Dictionary<int, int>();

                    // calculate paragraph relevance
                    for (int i = paraList.Count - 1; i >= 0; i--)
                    {
                        int countPreferUsage = 0;
                        string thisPara = paraList[i];
                        string parahash = getMD5Hash(thisPara);

                        // number of times the topic keyword occurs in the paragraph, takes high priority
                        int countTopic = (thisPara.Length - thisPara.ToLower().Replace(topic.ToLower(), "").Length) / topic.Length;
                        countPreferUsage += countTopic * 2;

                        // question marks and exclamation marks give demerit point (e.g. forum questions not proper posts)
                        int countMark = thisPara.Count(c => (c == '?' || c == '!'));
                        countPreferUsage -= countMark;

                        // number of times a preferred word occurs in the paragraph
                        foreach (var thisPunc in puncChars)
                        {
                            thisPara = thisPara.Replace(thisPunc, ' ');
                        }
                        var words = thisPara.Split(new char[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);
                        foreach (var word in words)
                        {
                            int countUsage = preferredWordList.Where(x => String.Compare(x, word, true) == 0).ToList().Count();
                            countPreferUsage += countUsage;
                        }
                        paraRelevant.Add(i, countPreferUsage);

                        if (!paraRelevantHash.ContainsKey(parahash))
                            paraRelevantHash.Add(parahash, countPreferUsage);

                        countNoURL++;
                    }

                    // only write topics that are considered significant
                    List<int> sortedPara = paraRelevant.Keys.ToList();
                    sortedPara.Sort((x1, x2) => paraRelevant[x2].CompareTo(paraRelevant[x1]));
                    foreach (var paraInd in sortedPara)
                    {
                        // only write down paragraphs which are more significant
                        int paraScore = paraRelevant[paraInd];
                        if (paraScore >= 5)
                        {
                            String para = paraList[paraInd];

                            if (retValByContent.ContainsKey(para) && !retValByContent[para].Contains(topic))
                            {
                                retValByContent[para].Add(topic);
                            }
                            else if (!retValByContent.ContainsKey(para))
                            {
                                List<string> topicList = new List<string>();
                                topicList.Add(topic);
                                retValByContent[para] = topicList;
                            }
                        }
                    }

                    countSelected++;
                }

                countProcessed++;
            }

            Console.WriteLine(String.Format("{0} - Done. {1} topics ({2} paragraphs) selected, {3} without URLs, {4} / {5} processed.", DateTime.Now, countSelected, retValByContent.Keys.Count, countNoURL, countProcessed, retValByTopic.Keys.Count));

            return retValByContent;
        }

        // a collection of strings is considered to be a poem
        // based on certain characteristics of line length 
        static bool isPoem(List<string> inputLines)
        {
            bool isValidPoem = true;
            inputLines = inputLines.Distinct().ToList();

            if (inputLines.Count >= 4)
            {
                List<int> lineLengths = new List<int>();
                foreach (var line in inputLines)
                {
                    if (line.EndsWith("...") || line.Contains(":") || (line.Length > 0 && !Char.IsUpper(line[0])))
                    {
                        isValidPoem = false;
                        break;
                    }


                    var words = line.Split(spaceChars, StringSplitOptions.RemoveEmptyEntries);
                    if (!lineLengths.Contains(words.Length))
                        lineLengths.Add(words.Length);

                    if (words.Length < 4 || words.Length > 14)
                    {
                        isValidPoem = false;
                        break;
                    }

                    var nameCount = 0;
                    for (int i = 0; i < words.Length; i++)
                    {
                        var thisWord = words[i];
                        if (Char.IsUpper(thisWord[0]))
                        {
                            nameCount++;
                        }

                        if (thisWord == thisWord.ToUpper())
                        {
                            isValidPoem = false;
                            break;
                        }
                    }

                    if (nameCount > 2)
                    {
                        isValidPoem = false;
                        break;
                    }
                }

                if (lineLengths.Count > 2)
                {
                    isValidPoem = false;
                }

                if (isValidPoem)
                {
                    var count = 0;
                    var lastCountLength = -1;
                    foreach (var length in lineLengths)
                    {
                        var countLength = inputLines.Count(line => line.Split(spaceChars, StringSplitOptions.RemoveEmptyEntries).Length == length);

                        if (countLength == 1 || (count > 0 && countLength != lastCountLength))
                        {
                            isValidPoem = false;
                            break;
                        }

                        count++;
                        lastCountLength = countLength;
                    }
                }
            }
            else
            {
                isValidPoem = false;
            }

            return isValidPoem;
        }

        static void getPoemContents(string inputFile)
        {
            List<List<string>> poemCollection = new List<List<string>>();

            List<string> currentPoem = new List<string>();
            int lastPoemIndex = Int32.MinValue;

            StreamReader sr = File.OpenText(inputFile);
            int curLine = 0;
            while (!sr.EndOfStream)
            {
                var fileLine = sr.ReadLine().Trim();

                if (fileLine.Length >= 32 && fileLine.Length <= 128)
                {
                    var countEnglish = fileLine.ToLower().Count(alphaNumericCharSet.Contains);
                    if (countEnglish * 100 / fileLine.Length >= 75)
                    {
                        // paragraphType = InputParagraphType.NonVietnamese;
                    }
                    else if (fileLine.Count(c => char.IsUpper(c)) >= 20)
                    {
                        // paragraphType = InputParagraphType.TooManyUpperCases;
                    }
                    else if (fileLine.Count(numericCharSet.Contains) > 0)
                    {
                        // paragraphType = InputParagraphType.DigitsOrSymbols;
                    }
                    else
                    {
                        bool isValid = false;
                        var sentences = fileLine.Split(new char[] { '.', '!', '?' }, StringSplitOptions.RemoveEmptyEntries);
                        if (sentences.Length == 1)
                        {
                            isValid = true;
                            foreach (var thisSentence in sentences)
                            {
                                var sentence = thisSentence.Trim();

                                var words = sentence.Split(new char[] { ' ', ',', ';', '-', ':' });
                                foreach (var word in words)
                                {
                                    // if there are long words, there could be problem with the paragraph (e.g. binary filtered not containing white space)
                                    if (word.Length > 20)
                                    {
                                        isValid = false;
                                        break;
                                    }
                                }
                            }

                            if (isValid)
                            {
                                // writeLog("Found possible poem phrase. ");

                                if (curLine - lastPoemIndex == 1)
                                {
                                    currentPoem.Add(fileLine);
                                }
                                else
                                {
                                    if (isPoem(currentPoem))
                                    {
                                        poemCollection.Add(currentPoem);
                                    }

                                    currentPoem = new List<string>();
                                    currentPoem.Add(fileLine);
                                }

                                lastPoemIndex = curLine;
                            }
                        }
                    }
                }

                curLine++;

            }
            sr.Close();

            if (isPoem(currentPoem))
                poemCollection.Add(currentPoem);

            foreach (var poem in poemCollection)
            {
                var newFileLine = String.Join("/", poem.ToArray());

                string lineHash = getMD5Hash(newFileLine);
                if (!paraPoemHash.ContainsKey(lineHash))
                    paraPoemHash.Add(lineHash, true);

                InputParagraphType paragraphType = InputParagraphType.Complete;
                if (sortedParagraphs.ContainsKey(paragraphType))
                {
                    sortedParagraphs[paragraphType].Add(newFileLine);
                }
                else
                {
                    List<string> paragraphs = new List<string>();
                    paragraphs.Add(newFileLine);
                    sortedParagraphs[paragraphType] = paragraphs;
                }

                // store where this sentence comes from, later to resolve the URL
                if (paragraphType == InputParagraphType.Complete)
                {
                    sortedParagraphSource.Add(sortedParagraphs[InputParagraphType.Complete].Count - 1, Path.GetFileNameWithoutExtension(inputFile));
                }
            }
        }

        static void getMeaningfulContents(string inputFile)
        {
            Regex urlRx = new Regex(@"(?<url>(http:[/][/]|www.)([a-z]|[A-Z]|[0-9]|[/.]|[~])*)", RegexOptions.IgnoreCase);

            StreamReader sr = File.OpenText(inputFile);
            while (!sr.EndOfStream)
            {
                var thisFileLine = sr.ReadLine();

                string fileLine = thisFileLine.Trim();
                InputParagraphType paragraphType = InputParagraphType.Undefined;
                if (fileLine.Length >= 128)
                {
                    if (urlRx.IsMatch(fileLine))
                    {
                        paragraphType = InputParagraphType.WithURLs;
                    }
                    else if (fileLine.Count(c => char.IsUpper(c)) >= 20)
                    {
                        paragraphType = InputParagraphType.TooManyUpperCases;
                    }
                    else if (fileLine.Count(numericCharSet.Contains) >= 20)
                    {
                        paragraphType = InputParagraphType.DigitsOrSymbols;
                    }
                    else
                    {
                        var sentences = fileLine.Split(new char[] { '.', '!', '?' }, StringSplitOptions.RemoveEmptyEntries);
                        if (sentences.Length < 3)
                        {
                            paragraphType = InputParagraphType.FewSentences;
                        }
                        else
                        {
                            int totalLength = 0;
                            foreach (var thisSentence in sentences)
                            {
                                var sentence = thisSentence.Trim();

                                // if there is a too long sentence, deem in unnatural and reject
                                // perhaps the paragraph is created due to text concatenation
                                if (sentence.Length >= 256)
                                {
                                    paragraphType = InputParagraphType.Concatenated;
                                    break;
                                }
                                else
                                {
                                    var words = sentence.Split(new char[] { ' ', ',', ';', '-', ':' });
                                    foreach (var word in words)
                                    {
                                        // if there are long words, there could be problem with the paragraph (e.g. binary filtered not containing white space)
                                        if (word.Length > 20)
                                        {
                                            paragraphType = InputParagraphType.Invalid;
                                            break;
                                        }
                                    }
                                }

                                totalLength += sentence.Length;
                            }

                            if (paragraphType == InputParagraphType.Undefined)
                            {
                                if (totalLength / sentences.Length < 20)
                                {
                                    paragraphType = InputParagraphType.ParagraphTooShort;
                                }
                                else
                                {
                                    if (Char.IsUpper(fileLine[0])) // paragraph beginning with upper case character, assuming full
                                    {
                                        if (paragraphType == InputParagraphType.Undefined)
                                        {
                                            paragraphType = InputParagraphType.Complete;
                                        }
                                    }
                                    else
                                    {
                                        // not capitalized or beginning with digit, most likey fragmented paragraph
                                        paragraphType = InputParagraphType.Fragmented;
                                    }
                                }
                            }
                        }
                    }
                }
                else
                {
                    paragraphType = InputParagraphType.ParagraphTooShort;
                }

                string newFileLine = "";
                if (paragraphType == InputParagraphType.Complete)
                {
                    var sentences = fileLine.Split(new char[] { '.' });
                    for (int i = 0; i < sentences.Length; i++)
                    {
                        var sentence = sentences[i];
                        if (sentence.Length > 0 && sentence.IndexOfAny(specialSymbol.ToArray()) < 0)
                        {
                            // remove sentences with special symbols (it may have been left-over from a menu, for example.
                            if (i > 0 && newFileLine.Length > 0)
                                newFileLine = newFileLine + ".";

                            // ignore first and last sentence if they are too short as these are usually redundant
                            if (i == 0 && sentence.Length <= 5)
                            {
                                // first sentence, e.g. A., B., C.
                                // Debug.WriteLine("here");
                            }
                            else if (i == sentences.Length - 1 && sentence.Length <= 15)
                            {
                                // last sentence, .e.g "read more"
                                // Debug.WriteLine("here");
                            }
                            else
                                newFileLine = newFileLine + sentence;
                        }
                    }
                }
                else
                {
                    newFileLine = fileLine;
                }

                if (newFileLine.Length > 64)
                {
                    if (sortedParagraphs.ContainsKey(paragraphType))
                    {
                        sortedParagraphs[paragraphType].Add(newFileLine);
                    }
                    else
                    {
                        List<string> paragraphs = new List<string>();
                        paragraphs.Add(fileLine);
                        sortedParagraphs[paragraphType] = paragraphs;
                    }

                    // store where this sentence comes from, later to resolve the URL
                    if (paragraphType == InputParagraphType.Complete)
                    {
                        sortedParagraphSource.Add(sortedParagraphs[InputParagraphType.Complete].Count - 1, Path.GetFileNameWithoutExtension(inputFile)); // index here starts from 0
                    }
                }
            }
            sr.Close();
        }

        static int countIgnored = 0;
        static int countAdded = 0;
        static int countTotal = 0;
        static int countDir = 0;

        static void AnalyzeDirectory(string sDir, string pattern)
        {            
            try
            {
                foreach (string file in Directory.GetFiles(sDir, pattern))
                {
                    if (countTotal % 100 == 0)
                    {
                        writeLog(String.Format("Added: {0}, Skipped: {1}. Total Files: {2}. Total Dirs: {3}", countAdded, countIgnored, countTotal, countDir));
                    }
                   
                    long fileSize = new FileInfo(file).Length;

                    // ignore too small or too big files
                    if (fileSize >= 4 * 1024 && fileSize <= 4 * 1024 * 1024)
                    {
                        getMeaningfulContents(file);
                        getPoemContents(file);
                        countAdded++;
                    }
                    else
                    {
                        countIgnored++;
                    }

                    countTotal++;
                }

                foreach (string d in Directory.GetDirectories(sDir))
                {
                    // Console.WriteLine(DateTime.Now + " - Reading " + d);
                    AnalyzeDirectory(d, pattern);
                    countDir++;
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(DateTime.Now + " - Error: " + ex.Message);
            }
        }

       static void ExtractTextToFile(string outputFile)
       {
            long count = 0;
            foreach (var paraType in sortedParagraphs.Keys)
            {
                List<string> paraList = sortedParagraphs[paraType];
                Console.WriteLine(String.Format("{0,20}: {1}", paraType, paraList.Count));
                count += paraList.Count;

                if (paraType == InputParagraphType.Complete)
                {
                    Console.WriteLine();
                    Console.WriteLine(String.Format("{0} - Analyzing complete paragraphs ...", DateTime.Now));
                    Console.WriteLine();

                    StringBuilder sb = new StringBuilder();
                    int paraCount = 0;

                    for (int i = 0; i < paraList.Count; i++) 
                    {
                        var paragraph = paraList[i];
                        var sourceName = sortedParagraphSource[i]; 

                        if (paraCount % 1000 == 0)
                            Console.WriteLine(String.Format("{0} - {1} / {2} paragraphs read. {3} poems ({4:0.00}%)", DateTime.Now, paraCount, sortedParagraphs[InputParagraphType.Complete].Count, paraPoemHash.Keys.Count,
                                paraCount * 100.0 / sortedParagraphs[InputParagraphType.Complete].Count));

                        var words = paragraph.Split(spaceChars, StringSplitOptions.RemoveEmptyEntries);

                        // if any of the forbidden word exists, we do not process the phrase
                        // the forbidden word contains expletive as well as name of some popular websites (these may exist as ads or remnants of the HTML-to-text process
                        bool isAvoided = false;
                        foreach (var thisWord in words)
                        {
                            if (avoidedWordList.Where(x => String.Compare(x.ToLower(), thisWord.ToLower()) == 0).ToList().Count() > 0)
                            {
                                isAvoided = true;
                                break;
                            }
                        }

                        if (!isAvoided)
                        {
                            extractedTextSource.Add(extractedTextSource.Keys.Count, sourceName);
                            sb.Append(paragraph+ Environment.NewLine);
                        }

                        paraCount++;
                    }

                    Console.WriteLine();
                    Console.WriteLine(String.Format("{0} - Done. {1} / {2} paragraphs read. {3} poems", DateTime.Now, paraCount, sortedParagraphs[InputParagraphType.Complete].Count, paraPoemHash.Keys.Count));
                    Console.WriteLine();

                    File.WriteAllText(outputFile, sb.ToString(), Encoding.UTF8);
                }
            }

            Console.WriteLine();
        }

        static List<string> findWordCombinations(string inputText, int minWords, int maxWords)
        {
            List<string> retval = new List<string>();

            // split by word
            var words = inputText.Split(spaceChars, StringSplitOptions.RemoveEmptyEntries);

            // identify proper names in the string
            String inputProperNames = "";
            String inputNoProperNames = "";

            for (int i=0;i<words.Length;i++)
            {
                var word = words[i].Trim();

                // word not first of sentence and not lower-case considered to be name
                bool isName = (i > 0 && word != word.ToLower());

                // word of long length that has no vietnamese character is considered to be English
                var countEnglish = word.ToLower().Count(alphaNumericCharSet.Contains);
                bool isEnglish = (word.Length >= 7 && countEnglish >= word.Length && word != word.ToLower());

                if (isEnglish)
                {
                    if (!retval.Contains(word))
                        retval.Add(word);

                    inputProperNames = inputProperNames + " ...";
                    inputNoProperNames = inputNoProperNames + " ...";
                }
                else if (isName)
                {
                    inputProperNames = inputProperNames + " " + word;
                    inputNoProperNames = inputNoProperNames + " ...";
                }
                else
                {
                    inputNoProperNames = inputNoProperNames + " " + word;
                    inputProperNames = inputProperNames + " ...";
                }
            }
            inputProperNames = inputProperNames.Trim();
            inputNoProperNames = inputNoProperNames.Trim();

            // word combinations that are proper names
            // hard code to between 2 and 3 words here to be meaningful
            List<string> retval1 = findWordCombinations2(inputProperNames, 2, 3, false);
            retval.AddRange(retval1);

            // other word combinations
            List<string> retval2 = findWordCombinations2(inputNoProperNames, minWords, maxWords, true);
            retval.AddRange(retval2);

            retval = retval.Distinct().ToList();
            return retval;
        }

        static List<string> findWordCombinations2(string inputText, int minWords, int maxWords, bool removeTitleCase)
        {
            List<string> allCombinations = new List<string>();

            try
            {
                // find long paragraphs in the original text only as short paragraph mostly contains fragment (links etc.) with keywords not relevant to the original content
                // var inputParagraph2 = String.Join("\n", inputText.Split(new char[] { '\n' }).Where(x => x.Length >= 128).ToArray());
                var inputParagraph2 = inputText;

                // TODO: String.Split() creates Unicode surrogate pairs accidentally
                var phrases = inputParagraph2.Split(puncChars.Union(new char[] { '\n' }).ToArray(), StringSplitOptions.RemoveEmptyEntries);

                foreach (var phrase in phrases)
                {
                    String tempPhrase = phrase.Trim();

                    if (tempPhrase.Length > 0)
                    {
                        var words = tempPhrase.Split(new char[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);
                        words = words.Where(x => !string.IsNullOrEmpty(x)).Select(x => x.Trim()).ToArray();

                        string currentPhrase = "";
                        for (int i = 0; i < words.Length; i++)
                        {
                            string thisWord = words[i];

                            // String.Length does not account for surrogate pairs; however, the StringInfo.LengthInTextElements method does.
                            // for example, "của".length = 5 (counting the accent marks if the file was saved in Unicode composite)
                            // Need String.Compare to cater for Unicode surrogate pairs. Normal == compare strings (used by List.Contains) as byte array
                            StringInfo si = new StringInfo(thisWord);
                            bool isValid = si.LengthInTextElements >= 2
                                            && thisWord != thisWord.ToUpper()
                                // && (i == 0 || thisWord == thisWord.ToLower())
                                            && !thisWord.Any(c => char.IsDigit(c))
                                            && ignoredWordList.Where(x => String.Compare(x.ToLower(), thisWord.ToLower()) == 0).ToList().Count() == 0;

                            if (!isValid || i == words.Length - 1)
                            {
                                // must be last word, append to phrase
                                if (isValid)
                                {
                                    currentPhrase = currentPhrase + " " + thisWord;
                                }

                                currentPhrase = currentPhrase.Trim();
                                int currentPhraseWordCount = currentPhrase.Split(new char[] { ' ' }, StringSplitOptions.RemoveEmptyEntries).Length;

                                if (currentPhrase.Length > 0 && currentPhraseWordCount >= minWords && currentPhraseWordCount <= maxWords && allCombinations.Where(x => String.Compare(x.ToLower(), currentPhrase.ToLower()) == 0).ToList().Count() == 0)
                                {
                                    if (removeTitleCase)
                                        currentPhrase = Char.ToLowerInvariant(currentPhrase[0]) + currentPhrase.Substring(1);

                                    allCombinations.Add(currentPhrase);
                                }
                                currentPhrase = "";
                            }
                            else if (isValid)
                            {
                                currentPhrase = currentPhrase + " " + thisWord;
                            }
                        }
                    }
                }

                allCombinations = allCombinations.OrderByDescending(x => x.Length).ToList();

                // remove any string that is substring of another string
                for (int i = allCombinations.Count - 1; i >= 0; i--)
                {
                    for (int j = i - 1; j >= 0; j--)
                    {
                        if (allCombinations[j].Contains(allCombinations[i], StringComparison.OrdinalIgnoreCase))
                        {
                            allCombinations.RemoveAt(i);
                            break;
                        }
                    }
                }

                // proper names go first, after that alphabetical
                allCombinations = allCombinations.OrderBy(x => x == x.ToLower()).ThenBy(x => x).ToList();
            }
            catch (Exception ex)
            {
                writeLog("findWordCombinations error: " + ex.Message);
            }

            return allCombinations;
        }

        static string getMD5Hash(string input)
        {
            StringBuilder sb = new StringBuilder();
            using (System.Security.Cryptography.MD5 md5 = System.Security.Cryptography.MD5.Create())
            {
                byte[] retVal = md5.ComputeHash(Encoding.Unicode.GetBytes(input));
                for (int i = 0; i < retVal.Length; i++)
                {
                    sb.Append(retVal[i].ToString("x2"));
                }
            }
            return sb.ToString();
        }

        static string formatPunctuation(string input)
        {
            var pattern = new Regex(@"\s+(\p{P})");
            var newString = pattern.Replace(input, "$1"); // remove space before punctuation           
            newString = Regex.Replace(newString, @"\.(?! |$)", ". "); // add space after every punctuations except those that already have space
            newString = Regex.Replace(newString, @"\,(?! |$)", ", ");

            // can't replace question mark, because the accent mark in "của" will be replaced as well, later it will cause EncoderFallbackException 
            // See http://stackoverflow.com/questions/10377189/encoderfallbackexception-while-writing-to-file - unicode surrogate pair mismatch when writing file
            // newString = Regex.Replace(newString, @"\\?(?! |$)", "? "); 

            newString = Regex.Replace(newString, @"\:(?! |$)", ": ");
            return newString;
        }

        static string StringToCSVCell(string str)
        {
            bool mustQuote = (str.Contains(",") || str.Contains("\"") || str.Contains("\r") || str.Contains("\n"));
            if (mustQuote)
            {
                StringBuilder sb = new StringBuilder();
                sb.Append("\"");
                foreach (char nextChar in str)
                {
                    sb.Append(nextChar);
                    if (nextChar == '"')
                        sb.Append("\"");
                }
                sb.Append("\"");
                return sb.ToString();
            }

            return str;
        }

        static void writeLog(string msg)
        {
            Console.WriteLine(DateTime.Now + " - " + msg);
        }
    }

    public static class StringExtensions
    {
        public static bool Contains(this string source, string toCheck, StringComparison comp)
        {
            return source.IndexOf(toCheck, comp) >= 0;
        }
    }
}
